spring.application.name=identity-core-service


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/identity_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.default_schema=identity_schema

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}

# Access Token Müddəti: 15 Dəqiqə (900000 ms)
security.jwt.access-token-expiration=900000

# Refresh Token Müddəti: 7 Gün (604800000 ms)
security.jwt.refresh-token-expiration=604800000